version: "3.3"

services:
  explorer:
    container_name: explorer
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - task-db
    networks:
      - backend

  task-db:
    container_name: task-db
    image: postgres:16
    volumes:
      - ./dbdata:/var/lib/pg
    env_file:
      - .development.env
    ports:
      - "5432:5432"
    networks:
      - backend

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    volumes:
      - ./swagger.yaml:/usr/share/nginx/swagger.yaml
    environment:
      - SWAGGER_JSON=/usr/share/nginx/swagger.yaml
    networks:
      - backend

networks:
  backend:
    driver: bridge